### ISSUE TITLE
Round End Report showing team hits

### ISSUE THREAD

**Issue by b1gwest** [KitsuneLab-Development/K4-DamageInfo#22] opened 2024-02-29 13:18 UTC
The round end reports are showing hits on team mates (I have team damage turned off on my server) so don't want to see hits on teammates. This is the current config settings I'm using for this plugin.

  _"round-end-summary": true,
  "round-end-summary-allow-death-print": true,
  "round-end-summary-show-all-damages": false,
  "round-end-summary-show-all-damages-enemies-only": true,
  "center-damage-info": false,
  "console-damage-info": true,
  "ffa-mode": false,
  "ConfigVersion": 2_

I would expect the setting   _"round-end-summary-show-all-damages-enemies-only": true_ to only show hits/damage for enemies, or maybe I am mis-interpreting what this setting is supposed to do.

Running plugin version 2.1.0

**Comment by K4ryuu** [comment] 2024-03-23 01:43
The problem is being fixed with the current release. Sorry it took so long, I didn't develop for a while, but I'm back on track.

**Comment by b1gwest** [comment] 2024-03-23 10:25
Thanks for looking at this. Unfortunately I still do not think it is fixed on new release.

I'm running latest 2.2.0 release
_[#2:LOADED]: "Damage Info" (2.2.0) by K4ryuu_

Here is my config

_// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4ryuuDamageInfo', at 2024/03/23 10:13:19
{
  "round-end-summary": true,
  "round-end-summary-allow-death-print": true,
  "round-end-summary-show-all-damages": false,
  "round-end-summary-show-all-damages-enemies-only": true,
  "center-damage-info": false,
  "console-damage-info": true,
  "ffa-mode": false,
  "norounds-mode": false,
  "center-info-flags": [
    "@myplugin/can-see-permission",
    "#myplugin/can-see-group",
    "can-see-override",
    "leave-empty-so-let-everyone-see"
  ],
  "ConfigVersion": 3
}_
![teamdmginfo](https://github.com/K4ryuu/CS2_DamageInfo/assets/161718738/650b5b74-8aac-49ae-b62e-a8e4b05edee9)

**Comment by K4ryuu** [comment] 2024-03-24 21:56
The problem being solved in the upcoming release with a new setting for team damage infos.
Thank you!

**Closed as completed by K4ryuu** 2024-03-24 21:56 UTC
Labels: bug
